name: cs234-project-env
channels:
  - pytorch
  - defaults
dependencies:
  - wheel<0.40.0
  - setuptools=65.5.0
  - pytorch
  - matplotlib
  - scipy
  - gitPython
  - gitdb2
  - tqdm
  - docopt
  - nltk
  - torchvision
  - torchaudio
  - pip=23.0
  - ipykernel
  - ipywidgets
  - pip:
    - gym==0.21
    - numpy==1.23.0
    - pybullet==3.2.6